### ISSUE TITLE
example 1 fails with "ValueError: math domain error" 

### ISSUE THREAD

**Issue by bgodard** [esa/pykep#75]
```python
$ python3 /local/scratch/bgodard/sw/anaconda3/lib/python3.6/site-packages/pykep/examples/_ex1.py
CMAES 4 PaGMO: 
mu: 10 - lambda: 20 - mueff: 5.9388 - N: 11
cc: 0.282335 - cs: 0.361861 - c1: 0.0127203 - cmu: 0.0469557 - sigma: 0.5 - damps: 1.36186 - chiN: 3.24255

   Gen:        Fevals:          Best:            dx:            df:         sigma:
      1              0        15468.6        2625.02    1.68662e+06            0.5
Traceback (most recent call last):
  File "/local/scratch/bgodard/sw/anaconda3/lib/python3.6/site-packages/pykep/examples/_ex1.py", line 39, in <module>
    run_example1()
  File "/local/scratch/bgodard/sw/anaconda3/lib/python3.6/site-packages/pykep/examples/_ex1.py", line 29, in run_example1
    pop = algo.evolve(pop)
  File "/local/scratch/bgodard/sw/anaconda3/lib/python3.6/site-packages/pykep/examples/_ex_utilities.py", line 17, in fitness
    return self.prob.fitness(x)
  File "/local/scratch/bgodard/sw/anaconda3/lib/python3.6/site-packages/pykep/trajopt/_pl2pl_N_impulses.py", line 98, in fitness
    T[i] = log(x[2 + 4 * i])
ValueError: math domain error
```
This is with anaconda packages:
```
pykep                     2.1                      py36_1    conda-forge
pagmo                     2.7                           0    conda-forge
pygmo                     2.7                      py36_0    conda-forge
```
on Redhat Linux 7.5.

Same problem on Ubuntu 18.04 freshly installed and up to date anaconda.

**Comment by darioizzo** [comment]
Might be just a missing guard on the domain of the log function which in some systems and runs happens .... I will try to reproduce this once I am done fixing the CI and py37 port

**Comment by darioizzo** [comment]
This is fixed now in #76. Will make a release soon containing a bunch of small things.

**Comment by darioizzo** [comment]
V2.2 is now available and released. It solves the issue. https://github.com/esa/pykep/releases/tag/v2.2

**Comment by darioizzo** [comment]
@bgodard can you confirm the issue is solved?

**Comment by bgodard** [comment]
Thank you for the fast fix.
Is this line 
```python
uda = pg.cmaes(gen=1000, force_bounds = True)
```
the only thing I need to change (I am using conda so I cannot easily test the latest git sources)?

Because if this is the case, it does not work for me. Still getting same error after adding the force_bounds = True

However in one case, I got a different error:
```python
$python3 _ex1_alt.py 
CMAES 4 PaGMO: 
mu: 10 - lambda: 20 - mueff: 5.9388 - N: 11
cc: 0.282335 - cs: 0.361861 - c1: 0.0127203 - cmu: 0.0469557 - sigma: 0.5 - damps: 1.36186 - chiN: 3.24255

   Gen:        Fevals:          Best:            dx:            df:         sigma:
      1              0          17665        3982.42         263135            0.5
Traceback (most recent call last):
  File "_ex1_alt.py", line 39, in <module>
    run_example1()
  File "_ex1_alt.py", line 29, in run_example1
    pop = algo.evolve(pop)
  File "/local/scratch/bgodard/sw/anaconda3/lib/python3.6/site-packages/pykep/examples/_ex_utilities.py", line 17, in fitness
    return self.prob.fitness(x)
  File "/local/scratch/bgodard/sw/anaconda3/lib/python3.6/site-packages/pykep/trajopt/_pl2pl_N_impulses.py", line 129, in fitness
    l = lambert_problem(rsc, r_target, dt, self.__common_mu, cw, False)
RuntimeError: Time of flight is negative!
```

**Comment by darioizzo** [comment]
On conda you should be able to get pykep 1.5 ... conda update pykep.

Did you try?

**Comment by bgodard** [comment]
Pykep is kept at version 2.1 because of the pygmo dependency.
I made a new conda env with pykep 2.2, but to install pygmo, conda wants to downgrade pykep ... but pygmo is needed for running the example.
